---
.travis.yml:
  deploy: false
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/spec_helper_acceptance.rb:
  spec_overrides:
    - "proj_root = File.expand_path(File.join(File.dirname(__FILE__), '..'))"
    - "copy_root_module_to(hosts, :source => File.join(proj_root, 'tests/site_munge'), :module_name => 'site_munge', :ignore_list => [])"
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
